package java_game;

/**
 *
 * @author anton0xf
 */
public class OtherPanel extends javax.swing.JPanel {

    private final FileStorage storage;

    /**
     * Creates new form OtherPanel
     */
    public OtherPanel(FileStorage storage) {
        this.storage = storage;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        buttonsPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        inputTextArea.setColumns(20);
        inputTextArea.setRows(5);
        jScrollPane1.setViewportView(inputTextArea);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonHandle(evt);
            }
        });
        buttonsPanel.add(saveButton);

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonHandle(evt);
            }
        });
        buttonsPanel.add(loadButton);

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonHandle(evt);
            }
        });
        buttonsPanel.add(clearButton);

        add(buttonsPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonHandle(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonHandle
        storage.save(inputTextArea.getText());
    }//GEN-LAST:event_saveButtonHandle

    private void loadButtonHandle(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonHandle
        inputTextArea.setText(storage.load());
    }//GEN-LAST:event_loadButtonHandle

    private void clearButtonHandle(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonHandle
        inputTextArea.setText("");
    }//GEN-LAST:event_clearButtonHandle


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
